engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  brakeman:
   	enabled: true
    #exclude_fingerprints:
    #- 08c185b3f764f262539a1f76997d3a89
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - ruby
ratings:
  paths:
  - web-app/app/**
  - web-app/lib/**
exclude_paths:
- web-app/spec/**/*
- "**/vendor/**/*"
- "web-app/web-app/assets/javascripts/graphs/"