FROM ruby:2.3.1

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  less \
  libpq-dev \
  nodejs

RUN ln -s /usr/bin/nodejs /usr/bin/node

ENV SHELL /bin/bash

RUN mkdir /app
WORKDIR /app

COPY Gemfile* /app/
RUN bundle install
