FROM ruby:2.3.1

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  less \
  libpq-dev \
  nodejs

RUN ln -s /usr/bin/nodejs /usr/bin/node

ENV SHELL /bin/bash

RUN mkdir /app
WORKDIR /app

RUN gem install bundler

COPY Gemfile* /app/
COPY config/application.yml /app/config/application.yml
RUN bundle install
RUN bundle update
